# Generated by Django 5.1.14 on 2025-11-28 14:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('ROTH_IRA', 'Roth IRA'), ('TRADITIONAL_IRA', 'Traditional IRA'), ('401K', '401(k)'), ('TAXABLE', 'Taxable')], max_length=20)),
                ('institution', models.CharField(max_length=100)),
                ('tax_treatment', models.CharField(choices=[('TAX_FREE', 'Tax Free'), ('TAX_DEFERRED', 'Tax Deferred'), ('TAXABLE', 'Taxable')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Asset class name (e.g., 'US Large Cap Stocks')", max_length=100, unique=True)),
                ('target_allocation_pct', models.DecimalField(decimal_places=2, help_text='Target allocation percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('expected_return', models.DecimalField(blank=True, decimal_places=2, help_text='Expected annual return (%)', max_digits=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Classes',
                'ordering': ['name'],
            },
        ),
    ]
