# Generated by Django 5.1.14 on 2025-12-16 18:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('tax_treatment', models.CharField(choices=[('TAX_FREE', 'Tax Free'), ('TAX_DEFERRED', 'Tax Deferred'), ('TAXABLE', 'Taxable')], max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_types', to='portfolio.accountgroup')),
            ],
        ),
        migrations.CreateModel(
            name='AllocationStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Allocation Strategy',
                'verbose_name_plural': 'Allocation Strategies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccountTypeStrategyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_assignments', to='portfolio.accounttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_type_strategy_assignments', to=settings.AUTH_USER_MODEL)),
                ('allocation_strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_type_assignments', to='portfolio.allocationstrategy')),
            ],
            options={
                'ordering': ['account_type__label'],
            },
        ),
        migrations.CreateModel(
            name='AssetClassCategory',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='portfolio.assetclasscategory')),
            ],
            options={
                'verbose_name': 'Asset Class Category',
                'verbose_name_plural': 'Asset Class Categories',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Asset class name (e.g., 'US Large Cap Stocks')", max_length=100, unique=True)),
                ('expected_return', models.DecimalField(blank=True, decimal_places=2, help_text='Expected annual return (%)', max_digits=5, null=True)),
                ('category', models.ForeignKey(db_column='category', help_text='Broad asset category', on_delete=django.db.models.deletion.PROTECT, related_name='asset_classes', to='portfolio.assetclasscategory')),
            ],
            options={
                'verbose_name_plural': 'Asset Classes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allocation_strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_assignments', to='portfolio.allocationstrategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='portfolio.accounttype')),
                ('allocation_strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_assignments', to='portfolio.allocationstrategy')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='portfolio.institution')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='securities', to='portfolio.assetclass')),
            ],
            options={
                'verbose_name_plural': 'Securities',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='RebalancingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('shares', models.DecimalField(decimal_places=4, max_digits=15)),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='portfolio.account')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.security')),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('as_of_date', models.DateField(auto_now=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.account')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='portfolio.security')),
            ],
            options={
                'ordering': ['account', 'security'],
            },
        ),
        migrations.CreateModel(
            name='TargetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.assetclass')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_allocations', to='portfolio.allocationstrategy')),
            ],
            options={
                'ordering': ['strategy', 'asset_class'],
            },
        ),
        migrations.AddConstraint(
            model_name='allocationstrategy',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_allocation_strategy_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='accounttypestrategyassignment',
            constraint=models.UniqueConstraint(fields=('user', 'account_type'), name='unique_account_type_strategy_assignment_per_user'),
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_portfolio_name_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together={('account', 'security')},
        ),
        migrations.AddConstraint(
            model_name='targetallocation',
            constraint=models.UniqueConstraint(fields=('strategy', 'asset_class'), name='unique_target_allocation_per_strategy_asset_class'),
        ),
    ]
