# Generated by Django 5.1.14 on 2025-11-28 19:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cost_basis', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('as_of_date', models.DateField(auto_now=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.account')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='portfolio.security')),
            ],
            options={
                'ordering': ['account', 'security'],
                'unique_together': {('account', 'security')},
            },
        ),
    ]
