# Generated by Django 5.1.14 on 2025-12-02 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holding',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.account'),
        ),
        migrations.AddField(
            model_name='rebalancingrecommendation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='portfolio.account'),
        ),
        migrations.AddField(
            model_name='security',
            name='asset_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='securities', to='portfolio.assetclass'),
        ),
        migrations.AddField(
            model_name='rebalancingrecommendation',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.security'),
        ),
        migrations.AddField(
            model_name='holding',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='portfolio.security'),
        ),
        migrations.AddField(
            model_name='targetallocation',
            name='asset_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.assetclass'),
        ),
        migrations.AddField(
            model_name='targetallocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together={('account', 'security')},
        ),
        migrations.AlterUniqueTogether(
            name='targetallocation',
            unique_together={('user', 'account_type', 'asset_class')},
        ),
    ]
