# Generated by Django 5.1.14 on 2025-11-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='cost_basis',
        ),
    ]
