# Generated by Django 6.0 on 2025-12-28 19:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_holding_shares_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, help_text='Price per share', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_datetime', models.DateTimeField(db_index=True, help_text='Market timestamp from data provider (actual market time)')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='When we fetched this price from data source (audit trail)')),
                ('source', models.CharField(choices=[('yfinance', 'Yahoo Finance'), ('manual', 'Manual Entry'), ('calculated', 'Calculated')], default='yfinance', help_text='Source of this price', max_length=20)),
                ('security', models.ForeignKey(help_text='Security this price belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='portfolio.security')),
            ],
            options={
                'verbose_name': 'Security Price',
                'verbose_name_plural': 'Security Prices',
                'ordering': ['-price_datetime'],
                'indexes': [models.Index(fields=['security', '-price_datetime'], name='portfolio_s_securit_24fd03_idx'), models.Index(fields=['price_datetime'], name='portfolio_s_price_d_3cf824_idx')],
                'unique_together': {('security', 'price_datetime')},
            },
        ),
    ]
