# Generated by Django 5.1.14 on 2025-12-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_add_user_relationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetclass',
            name='category',
            field=models.CharField(choices=[('US_EQUITIES', 'US Equities'), ('INTERNATIONAL_EQUITIES', 'International Equities'), ('FIXED_INCOME', 'Fixed Income'), ('REAL_ASSETS', 'Real Assets'), ('CASH', 'Cash')], default='US_EQUITIES', help_text='Broad asset category', max_length=32),
        ),
    ]
