# Generated by Django 5.1.14 on 2025-11-28 20:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_holding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetclass',
            name='target_allocation_pct',
        ),
        migrations.CreateModel(
            name='TargetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('ROTH_IRA', 'Roth IRA'), ('TRADITIONAL_IRA', 'Traditional IRA'), ('401K', '401(k)'), ('TAXABLE', 'Taxable')], help_text='Account type this allocation applies to', max_length=20)),
                ('target_pct', models.DecimalField(decimal_places=2, help_text='Target allocation percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('asset_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.assetclass')),
            ],
            options={
                'verbose_name_plural': 'Target Allocations',
                'ordering': ['account_type', 'asset_class'],
                'unique_together': {('account_type', 'asset_class')},
            },
        ),
    ]
