# Generated by Django 5.1.14 on 2025-11-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_holding_cost_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetclass',
            name='category',
            field=models.CharField(choices=[('EQUITIES', 'Equities'), ('FIXED_INCOME', 'Fixed Income'), ('REAL_ESTATE', 'Real Estate'), ('CASH', 'Cash')], default='EQUITIES', help_text='Broad asset category', max_length=20),
        ),
    ]
