# Generated by Django 6.0 on 2025-12-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_add_security_price_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='current_price',
        ),
    ]
