# Generated by Django 5.1.14 on 2025-11-28 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_assetclass_target_allocation_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebalancingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('shares', models.DecimalField(decimal_places=4, max_digits=15)),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='portfolio.account')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.security')),
            ],
        ),
    ]
