# Generated by Django 5.1.14 on 2025-11-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_assetclass_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetclass',
            name='category',
            field=models.CharField(choices=[('EQUITIES', 'Equities'), ('FIXED_INCOME', 'Fixed Income'), ('REAL_ASSETS', 'Real Assets'), ('CASH', 'Cash')], default='EQUITIES', help_text='Broad asset category', max_length=20),
        ),
    ]
