# Generated by Django 5.1.14 on 2025-12-03 01:45

from typing import Dict

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.state import StateApps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def seed_asset_categories(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    AssetCategory = apps.get_model('portfolio', 'AssetCategory')

    categories = [
        ('EQUITIES', 'Equities', None, 1),
        ('US_EQUITIES', 'US Equities', 'EQUITIES', 2),
        ('INTERNATIONAL_EQUITIES', 'International Equities', 'EQUITIES', 3),
        ('FIXED_INCOME', 'Fixed Income', None, 4),
        ('REAL_ASSETS', 'Real Assets', None, 5),
        ('CASH', 'Cash', None, 6),
    ]

    category_map: Dict[str, models.Model] = {}
    for code, label, parent_code, sort_order in categories:
        parent = category_map.get(parent_code) if parent_code else None
        category, _ = AssetCategory.objects.update_or_create(
            code=code,
            defaults={'label': label, 'parent': parent, 'sort_order': sort_order}
        )
        category_map[code] = category


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_assetclass_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='portfolio.assetcategory')),
            ],
            options={
                'verbose_name': 'Asset Category',
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.RunPython(seed_asset_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='assetclass',
            name='category',
            field=models.ForeignKey(db_column='category', help_text='Broad asset category', on_delete=django.db.models.deletion.PROTECT, related_name='asset_classes', to='portfolio.assetcategory'),
        ),
    ]
