# Generated by Django 5.1.14 on 2025-12-05 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_assetcategory_alter_assetclass_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='tax_treatment',
        ),
    ]
