# Generated by Django 6.0 on 2025-12-30 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_holding_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetclass',
            name='primary_security',
            field=models.ForeignKey(blank=True, help_text='Primary/preferred security for this asset class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_asset_classes', to='portfolio.security'),
        ),
    ]
