# Generated by Django 6.0 on 2026-01-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_assetclass_primary_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='security',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary security to use when opening new positions in this asset class'),
        ),
    ]
