# Generated by Django 6.0 on 2026-01-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_add_is_primary_to_security'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='securityprice',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='securityprice',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='securityprice_price_positive', violation_error_message='Price must be greater than zero'),
        ),
        migrations.AddConstraint(
            model_name='securityprice',
            constraint=models.UniqueConstraint(fields=('security', 'price_datetime'), name='unique_security_price_per_datetime', violation_error_message='A price already exists for this security at this datetime'),
        ),
    ]
