# Generated by Django 5.1.14 on 2025-12-05 21:16

from django.db import migrations

def populate_account_groups(apps, schema_editor):
    AccountGroup = apps.get_model('portfolio', 'AccountGroup')
    Account = apps.get_model('portfolio', 'Account')

    # Create Groups
    retirement = AccountGroup.objects.create(name='Retirement', sort_order=10)
    investments = AccountGroup.objects.create(name='Investments', sort_order=20)
    deposit = AccountGroup.objects.create(name='Deposit Accounts', sort_order=30)
    
    # Map Accounts
    # Retirement: ROTH_IRA, TRADITIONAL_IRA, 401K
    Account.objects.filter(account_type__in=['ROTH_IRA', 'TRADITIONAL_IRA', '401K']).update(group=retirement)
    
    # Investments: TAXABLE
    Account.objects.filter(account_type='TAXABLE').update(group=investments)

def reverse_populate_account_groups(apps, schema_editor):
    AccountGroup = apps.get_model('portfolio', 'AccountGroup')
    AccountGroup.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_accountgroup_account_group'),
    ]

    operations = [
        migrations.RunPython(populate_account_groups, reverse_populate_account_groups),
    ]
