# Generated by Django 5.1.14 on 2025-12-05 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_populate_account_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetallocation',
            name='asset_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_allocations', to='portfolio.assetclass'),
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('tax_treatment', models.CharField(choices=[('TAX_FREE', 'Tax Free'), ('TAX_DEFERRED', 'Tax Deferred'), ('TAXABLE', 'Taxable')], max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_types', to='portfolio.accountgroup')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_type_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='portfolio.accounttype'),
        ),
        migrations.AddField(
            model_name='targetallocation',
            name='account_type_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_allocations', to='portfolio.accounttype'),
        ),
    ]
