# Generated by Django 5.1.14 on 2025-12-05 21:35

from django.db import migrations

def migrate_account_types(apps, schema_editor):
    AccountType = apps.get_model('portfolio', 'AccountType')
    AccountGroup = apps.get_model('portfolio', 'AccountGroup')
    Account = apps.get_model('portfolio', 'Account')
    TargetAllocation = apps.get_model('portfolio', 'TargetAllocation')

    # Get Groups (assumes created by previous migration)
    retirement = AccountGroup.objects.get(name='Retirement')
    investments = AccountGroup.objects.get(name='Investments')
    # Default for now
    
    # Create Types
    # ROTH_IRA
    roth_ira, _ = AccountType.objects.get_or_create(
        code='ROTH_IRA',
        defaults={'label': 'Roth IRA', 'group': retirement, 'tax_treatment': 'TAX_FREE'}
    )
    
    # TRADITIONAL_IRA
    trad_ira, _ = AccountType.objects.get_or_create(
        code='TRADITIONAL_IRA',
        defaults={'label': 'Traditional IRA', 'group': retirement, 'tax_treatment': 'TAX_DEFERRED'}
    )
    
    # 401K
    k401, _ = AccountType.objects.get_or_create(
        code='401K',
        defaults={'label': '401(k)', 'group': retirement, 'tax_treatment': 'TAX_DEFERRED'}
    )

    # TAXABLE
    taxable, _ = AccountType.objects.get_or_create(
        code='TAXABLE',
        defaults={'label': 'Taxable', 'group': investments, 'tax_treatment': 'TAXABLE'}
    )
    
    # Map for easy lookup
    type_map = {
        'ROTH_IRA': roth_ira,
        'TRADITIONAL_IRA': trad_ira,
        '401K': k401,
        'TAXABLE': taxable,
    }

    # Migrate Accounts
    for account in Account.objects.all():
        if account.account_type in type_map:
            account.account_type_link = type_map[account.account_type]
            account.save()
            
    # Migrate TargetAllocations
    for target in TargetAllocation.objects.all():
        if target.account_type in type_map:
            target.account_type_link = type_map[target.account_type]
            target.save()

def reverse_migrate_account_types(apps, schema_editor):
    AccountType = apps.get_model('portfolio', 'AccountType')
    Account = apps.get_model('portfolio', 'Account')
    TargetAllocation = apps.get_model('portfolio', 'TargetAllocation')
    
    Account.objects.update(account_type_link=None)
    TargetAllocation.objects.update(account_type_link=None)
    AccountType.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_targetallocation_asset_class_accounttype_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_account_types, reverse_migrate_account_types),
    ]
