# Generated by Django 5.1.14 on 2025-12-05 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_migrate_account_types'),
    ]

    operations = [
        # Account
        migrations.RemoveField(
            model_name='account',
            name='account_type',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='account_type_link',
            new_name='account_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='group',
        ),
        
        # TargetAllocation
        # 1. Remove constraint that depends on 'account_type'
        migrations.AlterUniqueTogether(
            name='targetallocation',
            unique_together=set(),
        ),
        # 2. Remove the old field
        migrations.RemoveField(
            model_name='targetallocation',
            name='account_type',
        ),
        # 3. Rename the new field to 'account_type'
        migrations.RenameField(
            model_name='targetallocation',
            old_name='account_type_link',
            new_name='account_type',
        ),
        # 4. Re-add constraint (now refers to the new FK field)
        migrations.AlterUniqueTogether(
            name='targetallocation',
            unique_together={('user', 'account_type', 'asset_class')},
        ),
    ]
