# Generated by Django 5.1.14 on 2025-12-06 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_account_account_type_link_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='targetallocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='targetallocation',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Optional specific account override. If null, applies to the account type generally.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_allocations', to='portfolio.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='portfolio.accounttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='targetallocation',
            name='account_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='target_allocations', to='portfolio.accounttype'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='targetallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', True)), fields=('user', 'account_type', 'asset_class'), name='unique_default_target_allocation'),
        ),
        migrations.AddConstraint(
            model_name='targetallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', False)), fields=('user', 'account', 'asset_class'), name='unique_account_target_allocation'),
        ),
    ]
