# Generated by Django 5.1.14 on 2025-12-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_targetallocation_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssetCategory',
            new_name='AssetClassCategory',
        ),
        migrations.AlterModelOptions(
            name='assetclasscategory',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'Asset Class Category', 'verbose_name_plural': 'Asset Class Categories'},
        ),
    ]
